# Generated by Django 2.1a1 on 2018-08-12 16:26

import conference.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('webPage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission', models.BooleanField(default=True)),
                ('review', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=1000)),
                ('keywords', models.TextField(max_length=200)),
                ('file', models.FileField(upload_to=conference.models.upload_path)),
                ('status', models.IntegerField(default=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(to='conference.AuthorRecord')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='conference.ConferenceRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPaperRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallEvaluation', models.TextField()),
                ('point', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='conference.PaperRecord')),
                ('reviewCon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewCon', to='conference.ConferenceRecord')),
                ('reviewUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
