# Generated by Django 2.1.1 on 2018-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperrecord',
            name='abstract',
            field=models.TextField(max_length=2010),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='accepted',
            field=models.IntegerField(default=5),
        ),
    ]
