# Generated by Django 2.1.1 on 2018-10-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperrecord',
            old_name='review',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='conferencerecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reviewpaperrecord',
            name='accepted',
        ),
    ]
