# Generated by Django 2.1.1 on 2018-10-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrecord',
            name='email',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='authorrecord',
            name='mobileNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='overallEvaluation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='remark',
            field=models.CharField(default='', max_length=110),
        ),
    ]
