# Generated by Django 2.1a1 on 2018-08-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencerecord',
            name='description',
            field=models.CharField(max_length=1005),
        ),
        migrations.AlterField(
            model_name='conferencerecord',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
