# Generated by Django 2.1.1 on 2018-10-19 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencerecord',
            name='other_owner',
            field=models.ManyToManyField(related_name='other_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
