# Generated by Django 2.1a1 on 2018-08-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmemberrecord',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
