# Generated by Django 2.1a1 on 2018-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrecord',
            name='country',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='authorrecord',
            name='email',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='authorrecord',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='authorrecord',
            name='organization',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='conferencerecord',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paperrecord',
            name='abstract',
            field=models.TextField(max_length=1010),
        ),
        migrations.AlterField(
            model_name='paperrecord',
            name='keywords',
            field=models.TextField(max_length=210),
        ),
        migrations.AlterField(
            model_name='paperrecord',
            name='title',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='remark',
            field=models.CharField(max_length=110),
        ),
    ]
