# Generated by Django 2.1.1 on 2018-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20181019_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperrecord',
            name='remark',
            field=models.TextField(default=None, max_length=510),
        ),
        migrations.AlterField(
            model_name='pcmemberrecord',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='overallEvaluation',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='remark',
            field=models.CharField(default=None, max_length=510),
        ),
    ]
