# Generated by Django 2.1a1 on 2018-08-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0002_auto_20180812_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcMemberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcCon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcCon', to='conference.ConferenceRecord')),
                ('pcUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
