# Generated by Django 2.1a1 on 2018-08-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_pcmemberrecord_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpaperrecord',
            name='accepted',
            field=models.IntegerField(default=3),
        ),
    ]
