# Generated by Django 2.1a1 on 2018-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20180809_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperrecord',
            name='review',
        ),
    ]
