# Generated by Django 2.1a1 on 2018-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conference', '0002_auto_20180822_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencerecord',
            name='name',
            field=models.CharField(max_length=151),
        ),
    ]
