# Generated by Django 2.1a1 on 2018-08-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_pcmemberrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpaperrecord',
            name='reviewUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewUser', to='conference.PcMemberRecord'),
        ),
    ]
