# Generated by Django 2.1a1 on 2018-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_reviewpaperrecord_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperrecord',
            name='review',
            field=models.TextField(default='', max_length=510),
        ),
    ]
