# Generated by Django 2.1a1 on 2018-08-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conference', '0003_auto_20180822_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmemberrecord',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
