# Generated by Django 2.1a1 on 2018-08-08 20:18

import conference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_remove_paperrecord_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperrecord',
            name='file',
            field=models.FileField(upload_to=conference.models.upload_path),
        ),
    ]
