# Generated by Django 2.1a1 on 2018-08-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conference', '0004_pcmemberrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmemberrecord',
            name='totalPaper',
            field=models.IntegerField(default=0),
        ),
    ]
