# Generated by Django 2.1a1 on 2018-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_paperrecord_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencerecord',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
