# Generated by Django 2.1a1 on 2018-08-23 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('conference', '0005_pcmemberrecord_totalpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmemberrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
