# Generated by Django 2.1a1 on 2018-08-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20180809_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpaperrecord',
            name='reviewCon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewCon', to='conference.ConferenceRecord'),
        ),
    ]
