# Generated by Django 2.1a1 on 2018-08-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conference', '0006_pcmemberrecord_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcmemberrecord',
            name='accepted',
            field=models.IntegerField(default=0),
        ),
    ]
