# Generated by Django 2.1a1 on 2018-08-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_pcmemberrecord_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpaperrecord',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
